services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=resource-server-db'
      - 'MONGO_INITDB_ROOT_PASSWORD=bimatnha'
      - 'MONGO_INITDB_ROOT_USERNAME=phatdo'
    ports:
      - '24017:27017'
