spring:
  application:
    name: resource-server
  data: 
    mongodb:
      uri: mongodb://localhost:27017/resource-server-db
  security:
    oauth2:
      resource-server:
        jwt:
          jwt-set-uri: http://127.0.0.1:9000/oauth2/jwks
  profiles:
    include:
      - secret
server:
  port: 9090